### ISSUE TITLE
`awscc_gamelift_fleet` forcing resource replacement when no values have changed

### ISSUE THREAD

**Issue by novekm** [hashicorp/terraform-provider-awscc#1428] opened 2024-02-13 03:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* `awscc_gamelift_fleet`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "awscc_gamelift_fleet" "example" {
  name              = "TFExampleFleet"
  build_id          = awscc_gamelift_build.example.id
  compute_type      = "EC2"
  ec2_instance_type = "c5.large"
  fleet_type        = "ON_DEMAND"
  
  runtime_configuration = {
    server_processes = [
      {
        concurrent_executions = 1
        launch_path           = "/local/game/gamelift-test-app"
        parameters            = "port:1936 gameSessionLengthSeconds:20"
      },

    ]
  }
}

resource "awscc_gamelift_build" "example" {
  name             = "ExampleBuild"
  version          = "1.0"
  operating_system = "AMAZON_LINUX_2"
  server_sdk_version = "5.1.1"

  storage_location = {
    bucket   = "gamelift-test-kevon"
    key      = "gamelift-test-app-cpp-5.x-linux-x64-static-gcc-std.zip"
    role_arn = awscc_iam_role.example.arn
  }
}


resource "awscc_iam_role" "example" {
  role_name                   = "gamelift-s3-access"
  description                 = "This IAM role grants Amazon GameLift access to the S3 bucket containing build files"
  assume_role_policy_document = data.aws_iam_policy_document.instance_assume_role_policy.json
  managed_policy_arns         = [aws_iam_policy.example.arn]
  max_session_duration        = 7200
  path                        = "/"
  tags = [
    {
      key   = "Environment"
      value = "Development"
    },
    {
      key   = "Modified By"
      value = "AWSCC"
    }
  ]
}

data "aws_iam_policy_document" "instance_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["gamelift.amazonaws.com"]
    }
  }
}

resource "aws_iam_policy" "example" {
  name = "gamelift-s3-access-policy"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["s3:*"]
        Resource = "*"
      },
    ]
  })
}
```

### Debug Output

https://gist.github.com/novekm/9d9ff0a3e0954c9c5e1b08f3702dd82c

### Expected Behavior

Since the optional values for this resource were omitted, they were set to `null` by the provider. These values (as well as the other values) were added to the Terraform State when the resource was created successfully. Terraform should have noticed that these optional values are defined in the state file, and should not force recreation since none of the values have changed since the last apply. This is the same functionality that applies with the [`awscc_gamelift_build` resource](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/gamelift_build) when omitting optional attributes. For that resource, Terraform recognizes that the optional values were not present in the config (and are set to `null` or a default value in the state) and a subsequent `terraform plan` shows that no changes will be made.

Here is the state file after creating the `awscc_gamelift_fleet`:
```hcl
{
      "mode": "managed",
      "type": "awscc_gamelift_fleet",
      "name": "example",
      "provider": "provider[\"registry.terraform.io/hashicorp/awscc\"]",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "anywhere_configuration": null,
            "apply_capacity": null,
            "build_id": "build-79fb6d85-70e9-4bb3-b484-0481e0b171ca",
            "certificate_configuration": {
              "certificate_type": "DISABLED"
            },
            "compute_type": "EC2",
            "description": null,
            "desired_ec2_instances": null,
            "ec2_inbound_permissions": null,
            "ec2_instance_type": "c5.large",
            "fleet_id": "fleet-dba2eed1-038e-49f7-a685-ebfcb306e63d",
            "fleet_type": "ON_DEMAND",
            "id": "fleet-dba2eed1-038e-49f7-a685-ebfcb306e63d",
            "instance_role_arn": null,
            "instance_role_credentials_provider": null,
            "locations": [
              {
                "location": "us-west-2",
                "location_capacity": null
              }
            ],
            "log_paths": null,
            "max_size": null,
            "metric_groups": [
              "default"
            ],
            "min_size": null,
            "name": "TFExampleFleet",
            "new_game_session_protection_policy": "NoProtection",
            "peer_vpc_aws_account_id": null,
            "peer_vpc_id": null,
            "resource_creation_limit_policy": null,
            "runtime_configuration": {
              "game_session_activation_timeout_seconds": 30,
              "max_concurrent_game_session_activations": 2147483647,
              "server_processes": [
                {
                  "concurrent_executions": 1,
                  "launch_path": "/local/game/gamelift-test-app",
                  "parameters": "port:1936 gameSessionLengthSeconds:20"
                }
              ]
            },
            "scaling_policies": null,
            "script_id": null,
            "server_launch_parameters": "port:1936 gameSessionLengthSeconds:20",
            "server_launch_path": "/local/game/gamelift-test-app"
          },
          "sensitive_attributes": [],
          "dependencies": [
            "aws_iam_policy.example",
            "awscc_gamelift_build.example",
            "awscc_iam_role.example",
            "data.aws_iam_policy_document.instance_assume_role_policy"
          ]
        }
      ]
    },
```

### Actual Behavior

After successfully creating the `awscc_gamelift_fleet`, any subsequent `terraform plan` shows that the entire resource must be replaced, even though no changes have been made to the configuration files or any of the attributes that would force resource replacement.

`terraform plan` after resource creation:
```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # awscc_gamelift_fleet.example must be replaced
-/+ resource "awscc_gamelift_fleet" "example" {
      + anywhere_configuration             = (known after apply)
      + apply_capacity                     = (known after apply) # forces replacement
      ~ certificate_configuration          = {
          ~ certificate_type = "DISABLED" -> (known after apply)
        } -> (known after apply)
      + description                        = (known after apply)
      + desired_ec2_instances              = (known after apply)
      + ec2_inbound_permissions            = (known after apply)
      ~ fleet_id                           = "fleet-dba2eed1-038e-49f7-a685-ebfcb306e63d" -> (known after apply)
      ~ id                                 = "fleet-dba2eed1-038e-49f7-a685-ebfcb306e63d" -> (known after apply)
      + instance_role_arn                  = (known after apply) # forces replacement
      + instance_role_credentials_provider = (known after apply) # forces replacement
      ~ locations                          = [
          - {
              - location = "us-west-2" -> null
            },
        ] -> (known after apply)
      + log_paths                          = (known after apply) # forces replacement
      + max_size                           = (known after apply)
      ~ metric_groups                      = [
          - "default",
        ] -> (known after apply)
      + min_size                           = (known after apply)
        name                               = "TFExampleFleet"
      ~ new_game_session_protection_policy = "NoProtection" -> (known after apply)
      + peer_vpc_aws_account_id            = (known after apply) # forces replacement
      + peer_vpc_id                        = (known after apply) # forces replacement
      + resource_creation_limit_policy     = (known after apply)
      ~ runtime_configuration              = {
          ~ game_session_activation_timeout_seconds = 30 -> (known after apply)
          ~ max_concurrent_game_session_activations = 2147483647 -> (known after apply)
            # (1 unchanged attribute hidden)
        }
      + scaling_policies                   = (known after apply)
      + script_id                          = (known after apply) # forces replacement
      ~ server_launch_parameters           = "port:1936 gameSessionLengthSeconds:20" -> (known after apply)
      ~ server_launch_path                 = "/local/game/gamelift-test-app" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

  # awscc_iam_role.example will be updated in-place
  ~ resource "awscc_iam_role" "example" {
      ~ assume_role_policy_document = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = "sts:AssumeRole"
                        Effect    = "Allow"
                        Principal = {
                            Service = "gamelift.amazonaws.com"
                        }
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        id                          = "gamelift-s3-access"
      + permissions_boundary        = (known after apply)
      + policies                    = (known after apply)
        tags                        = [
            {
                key   = "Modified By"
                value = "AWSCC"
            },
            {
                key   = "Environment"
                value = "Development"
            },
        ]
        # (7 unchanged attributes hidden)
    }

Plan: 1 to add, 1 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by wellsiau-aws** [comment] 2024-02-13 23:35
might be related to similar issue on #983, @novekm are you able to compare the resource using AWS CLI vs HCL config and Terraform State ?

**Comment by wellsiau-aws** [comment] 2024-02-14 01:11
[Debug logs](https://gist.github.com/novekm/9d9ff0a3e0954c9c5e1b08f3702dd82c) seems to indicate that certain attribute has changed

```
2024-02-13T02:52:25.073Z [DEBUG] provider.terraform-provider-awscc_v0.70.0_x5: Detected value change between proposed new state and prior state: tf_rpc=PlanResourceChange @caller=github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_planresourcechange.go:186 tf_attribute_path=certificate_configuration tf_resource_type=awscc_gamelift_fleet tf_req_id=deca06f2-3217-dfc1-26d1-862bca62ec94 @module=sdk.framework tf_provider_addr=registry.terraform.io/hashicorp/awscc timestamp=2024-02-13T02:52:25.073Z
```

In specific the attribute in question is : `certificate_configuration`

**Comment by novekm** [comment] 2024-02-20 02:39
As of my testing today, it looks like you have to also explicitly define the `location_capacity` (another optional value) or it again states the resource must be force recreated. I thought this could potentially be a provider version issue, but same happens on v0.66.0 as well as v0.70.0. 

**My new config looks like this and does not cause force recreation**:
```hcl
resource "awscc_gamelift_fleet" "example" {
  name              = "TFExampleFleet"
  build_id          = awscc_gamelift_build.example.id
  compute_type      = "EC2"
  ec2_instance_type = "c5.large"
  fleet_type        = "ON_DEMAND"
  # description = "hi"
  
  runtime_configuration = {
    server_processes = [
      {
        concurrent_executions = 1
        launch_path           = "/local/game/gamelift-test-app"
        parameters            = "port:1936 gameSessionLengthSeconds:20"
      },

    ]
  }
  
  ec2_inbound_permissions = [
    {
      from_port : 8101,
      ip_range : "70.127.195.133/32",
      protocol : "UDP",
      to_port : 8999
    },
    {
      from_port : 22,
      ip_range : "70.127.195.133/32",
      protocol : "TCP",
      to_port : 22
    },
  ]
  
  locations = [{
    location = "us-west-2",
    location_capacity = {
      desired_ec2_instances = 1
      max_size = 1
      min_size = 0
    }
  }]
  
  certificate_configuration = {
    certificate_type = "DISABLED"
  }
}
```
**Which gives the following when running `terraform plan`**:
```hcl
Terraform will perform the following actions:

  # awscc_iam_role.example will be updated in-place
  ~ resource "awscc_iam_role" "example" {
      ~ assume_role_policy_document = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = "sts:AssumeRole"
                        Effect    = "Allow"
                        Principal = {
                            Service = "gamelift.amazonaws.com"
                        }
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        id                          = "gamelift-s3-access"
      + permissions_boundary        = (known after apply)
      + policies                    = (known after apply)
        tags                        = [
            {
                key   = "Modified By"
                value = "AWSCC"
            },
            {
                key   = "Environment"
                value = "Development"
            },
        ]
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```
I thought that adding the (optional) values `locations` and `certificate_configuration` would be a temporary solution, however when making changes to another optional value such as `description`, `terraform plan` shows that it again must be destroyed and recreated. See the below for the new config/plan

**TF Config (with optional description added)**
```hcl
resource "awscc_gamelift_fleet" "example" {
  name              = "TFExampleFleet"
  build_id          = awscc_gamelift_build.example.id
  compute_type      = "EC2"
  ec2_instance_type = "c5.large"
  fleet_type        = "ON_DEMAND"
  description = "hi"
  
  runtime_configuration = {
    server_processes = [
      {
        concurrent_executions = 1
        launch_path           = "/local/game/gamelift-test-app"
        parameters            = "port:1936 gameSessionLengthSeconds:20"
      },

    ]
  }
  
  ec2_inbound_permissions = [
    {
      from_port : 8101,
      ip_range : "70.127.195.133/32",
      protocol : "UDP",
      to_port : 8999
    },
    {
      from_port : 22,
      ip_range : "70.127.195.133/32",
      protocol : "TCP",
      to_port : 22
    },
  ]
  
  locations = [{
    location = "us-west-2",
    location_capacity = {
      desired_ec2_instances = 1
      max_size = 1
      min_size = 0
    }
  }]
  
  certificate_configuration = {
    certificate_type = "DISABLED"
  }
}
```

**The subsequent `terraform plan` shows the following**:
```hcl
Terraform will perform the following actions:

  # awscc_gamelift_fleet.example must be replaced
-/+ resource "awscc_gamelift_fleet" "example" {
      + anywhere_configuration             = (known after apply)
      + apply_capacity                     = (known after apply) # forces replacement
      + description                        = "hi"
      + desired_ec2_instances              = (known after apply)
      ~ fleet_id                           = "fleet-b5d0550c-6bbc-4dbd-bd84-a84e0b11f22e" -> (known after apply)
      ~ id                                 = "fleet-b5d0550c-6bbc-4dbd-bd84-a84e0b11f22e" -> (known after apply)
      + instance_role_arn                  = (known after apply) # forces replacement
      + instance_role_credentials_provider = (known after apply) # forces replacement
      + log_paths                          = (known after apply) # forces replacement
      + max_size                           = (known after apply)
      ~ metric_groups                      = [
          - "default",
        ] -> (known after apply)
      + min_size                           = (known after apply)
        name                               = "TFExampleFleet"
      ~ new_game_session_protection_policy = "NoProtection" -> (known after apply)
      + peer_vpc_aws_account_id            = (known after apply) # forces replacement
      + peer_vpc_id                        = (known after apply) # forces replacement
      + resource_creation_limit_policy     = (known after apply)
      ~ runtime_configuration              = {
          ~ game_session_activation_timeout_seconds = 30 -> (known after apply)
          ~ max_concurrent_game_session_activations = 2147483647 -> (known after apply)
            # (1 unchanged attribute hidden)
        }
      + scaling_policies                   = (known after apply)
      + script_id                          = (known after apply) # forces replacement
      ~ server_launch_parameters           = "port:1936 gameSessionLengthSeconds:20" -> (known after apply)
      ~ server_launch_path                 = "/local/game/gamelift-test-app" -> (known after apply)
        # (7 unchanged attributes hidden)
    }
```

**Comment by ewbankkit** [comment] 2024-02-22 17:54
These are the properties any of which will force recreation if Terraform detects a change:

```json
  "createOnlyProperties": [
    "/properties/ApplyCapacity",
    "/properties/BuildId",
    "/properties/CertificateConfiguration",
    "/properties/EC2InstanceType",
    "/properties/FleetType",
    "/properties/InstanceRoleARN",
    "/properties/InstanceRoleCredentialsProvider",
    "/properties/LogPaths",
    "/properties/PeerVpcAwsAccountId",
    "/properties/PeerVpcId",
    "/properties/ScriptId",
    "/properties/ServerLaunchParameters",
    "/properties/ServerLaunchPath",
    "/properties/CertificateType",
    "/properties/ComputeType"
  ],
```

**Comment by ewbankkit** [comment] 2024-02-22 18:02
The root cause of the issue with `Locations` is discussed (at length) here: https://discuss.hashicorp.com/t/dealing-with-unordered-sets-of-complex-objects-setnestedattribute-with-computed-attributes/61874.

`Locations` is a list of objects that include `Computed/Optional` attributes and because the underlying array is marked with `"insertionOrder": false` we have the same problems as described with `TypeSet`s.
Explicitly adding all attributes that are returned with defaults _should_ work around this.

**Comment by wellsiau-aws** [comment] 2024-02-26 16:36
@ewbankkit , make sense for the `locations` since its a list of objects. 

however we also encounter this problem with `certificate_configuration`, I suspect that has different root cause?

**Comment by wellsiau-aws** [comment] 2024-02-26 23:43
We believe there are two root cause issue here. 

We dont know yet why `certificate_configuration` triggers replacement and we'll investigate it separately on different GH issue.

Issue #1428 will focus solely on one of the root cause: **unordered complex object with computed attributes.**

**Comment by wellsiau-aws** [comment] 2024-03-28 04:05
Closing this issue now, I can confirm that problem with unordered complex object is now fixed. This will address problem with `locations`  attribute.

I've opened separate issue to track problem when other mutating attributes trigger force replacement in #1497

**Closed by wellsiau-aws** 2024-03-28 04:05 UTC
Labels: bug, service/gamelift
