### ISSUE TITLE
core network configuration rejects a valid policy document

### ISSUE THREAD

**Issue by alphabyr** [hashicorp/terraform-provider-awscc#550] opened 2022-06-15 11:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.18.0
+ provider registry.terraform.io/hashicorp/awscc v0.24.0

### Affected Resource(s)

* awscc_networkmanager_core_network
* aws_networkmanager_core_network_policy_document

### Terraform Configuration Files

* providers.tf
```

terraform {
  required_version = ">= 1.2.2"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.9.0"
    }
    awscc = {
      source  = "hashicorp/awscc"
      version = ">= 0.21.0"
    }
  }
}

provider "aws" {
  region  = "us-east-1"
  profile = "test"
}

provider "awscc" {
  region  = "us-east-1"
  profile = "test"
}
```

* cloudwan.tf
```

locals {
  terraform_tag = [{
    key   = "terraform"
    value = "true"
  }]
}

resource "awscc_networkmanager_global_network" "main" {
  description = "My Global Network"
  tags = concat(local.terraform_tag,
    [{
      key   = "Name"
      value = "My Global Network"
    }]
  )

  provider = awscc
}

resource "awscc_networkmanager_core_network" "main" {
  description       = "My Core Network"
  global_network_id = awscc_networkmanager_global_network.main.id
  # Compose jsonencode and jsondecode to produce a normalized JSON string.
  policy_document = jsonencode(jsondecode(data.aws_networkmanager_core_network_policy_document.main.json))
  tags            = local.terraform_tag
  
  provider = awscc
}

data "aws_networkmanager_core_network_policy_document" "main" {
  core_network_configuration {
    vpn_ecmp_support = false
    asn_ranges       = ["64512-64555"]
    edge_locations {
      location = "us-east-1"
      asn      = 64512
    }
  }

  segments {
    name                          = "shared"
    description                   = "SegmentForSharedServices"
    require_attachment_acceptance = true
  }

  segment_actions {
    action     = "share"
    mode       = "attachment-route"
    segment    = "shared"
    share_with = ["*"]
  }

  attachment_policies {
    rule_number     = 1
    condition_logic = "or"

    conditions {
      type     = "tag-value"
      operator = "equals"
      key      = "segment"
      value    = "shared"
    }
    action {
      association_method = "constant"
      segment            = "shared"
    }
  }

  provider = aws
}
```

### Debug Output

https://gist.github.com/alphabyr/a4d1992630a2cf24fc9cd6a7927e4d92

### Panic Output

N/A

### Expected Behavior

This code was copied/pasted directly from https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/guides/using-aws-with-awscc-provider
and the plan should create a cloudwan global network, and a core network based on an aws_networkmanager_core_network_policy_document resource

### Actual Behavior

Instead, the plan only creates the global network and the core network creation fails due to an error on the policy_document attribute even though the whole piece of code was taken directly from the official documentation.

```
awscc_networkmanager_core_network.main: Creating...
╷
│ Error: AWS SDK Go Service Operation Unsuccessful
│ 
│   with awscc_networkmanager_core_network.main,
│   on cloudwan.tf line 20, in resource "awscc_networkmanager_core_network" "main":
│   20: resource "awscc_networkmanager_core_network" "main" {
│ 
│ Calling Cloud Control API service CreateResource operation returned: operation error CloudControl: CreateResource, https response error StatusCode: 400, RequestID:
│ 503b263e-6f28-4bfe-b1d5-c0f88ad9c401, api error ValidationException: Model validation failed (#/PolicyDocument: expected type: JSONObject, found: String)
```

### Steps to Reproduce

1. `terraform apply` 
2. the global network will be created 
3. the core network creation fails due to the policy document

### Important Factoids

The code uses an AWS authentication profile named "test"

### References

* https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/guides/using-aws-with-awscc-provider

**Comment by ewbankkit** [comment] 2022-06-20 18:44
@alphabyr Thanks for raising this issue 👏 .
The problem is caused by a change to the `AWS::NetworkManager::CoreNetwork` resource type's `PolicyDocument` property.
In the *v0.24.0** of the provider it has been declared as a `string` but since that version's release the CloudFormation resource schema definition has changed to type `object` (a JSON string): https://github.com/hashicorp/terraform-provider-awscc/pull/555.
This is being addressed in https://github.com/hashicorp/terraform-provider-awscc/pull/537.

**Closed** 2022-06-20 19:23 UTC
