### ISSUE TITLE
OpensearchServerless collection, changes to Tags causes full resource rebuild

### ISSUE THREAD

**Issue by joshtrutwin** [hashicorp/terraform-provider-awscc#871] opened 2023-03-14 17:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_opensearchserverless_collection

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Create an Opensearch Serverless collection using minimal configuration:

resource "awscc_opensearchserverless_collection" "aoss_collection" {
  name        = "test-collection"
  description = "Test Collection"
  type        = "SEARCH"

  tags =  [
      { key : "Application", value : "TestApplication" },
  ]
}

# Attempt to update one of the tags (or add/delete tags):

resource "awscc_opensearchserverless_collection" "aoss_collection" {
  name        = "test-collection"
  description = "Test Collection"
  type        = "SEARCH"

  tags =  [
      { key : "Application", value : "Test Application" },
  ]
}

# run terraform plan
```

### Expected Behavior

The awscc_opensearchserverless_collection resource should be an update-in-place.  You should be able to update tags on any AWS resources without recreation.

### Actual Behavior

The plan (and apply if run) attempt to re-create the entire collection resouce:

``` 
Terraform will perform the following actions:

  # awscc_opensearchserverless_collection.aoss_collection must be replaced
-/+ resource "awscc_opensearchserverless_collection" "aoss_collection" {
      ~ arn                 = "arn:aws:aoss:us-east-2:<snipped>:collection/<snipped>" -> (known after apply)
      ~ collection_endpoint = "https://<snipped>.us-east-2.aoss.amazonaws.com" -> (known after apply)
      ~ dashboard_endpoint  = "https://<snipped>.us-east-2.aoss.amazonaws.com/_dashboards" -> (known after apply)
      ~ id                  = "<snipped>" -> (known after apply)
        name                = "test-collection"
      ~ tags                = [ # forces replacement
          ~ {
              ~ value = "TestApplication" -> "Test Application"
                # (1 unchanged attribute hidden)
            },
            # (10 unchanged elements hidden)
        ]
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. Create a collection using terraform with the AWSCC resource type
2. Attempt to update tags parameter in terraform in any way
3. `terraform plan`

### Important Factoids

Works via API call in cloudshell, only an issue with the awscc collection resource type:

```
[cloudshell-user@ip-10-x-y-z ~]$ aws opensearchserverless tag-resource --resource-arn "arn:aws:aoss:us-east-2:<snip>:collection/<snip>" --tags key=Application,value="New Test Application Tag Value"
```

Change shows up in Collection tags in UI.

### References

I believe the issue is that the update-collection API call does not provide a direct way to update tags so you have to use that tag-resource call instead:

https://docs.aws.amazon.com/opensearch-service/latest/ServerlessAPIReference/API_UpdateCollection.html
https://docs.aws.amazon.com/opensearch-service/latest/ServerlessAPIReference/API_TagResource.html

Note that TagResource lets you update an already created tag.

* #0000

**Comment by breathingdust** [comment] 2023-03-22 14:54
Hi @joshtrutwin, `tags` in this resource are marked as create only by the CloudFormation schema, so the behaviour you are describing is expected and not a bug:

https://github.com/hashicorp/terraform-provider-awscc/blob/56d25629969a7f9fadeede063563bee444144d64/internal/service/cloudformation/schemas/AWS_OpenSearchServerless_Collection.json#L4-L10

I would raise a support case with AWS if you would like to see this behaviour changed.

**Closed by breathingdust** 2023-03-22 14:54 UTC
Labels: needs-triage
