### ISSUE TITLE
AWSCC provider now panics if 'optional' duration not set in assume-role

### ISSUE THREAD

**Issue by voidshard** [hashicorp/terraform-provider-awscc#1809] opened 2024-06-11 09:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

- terraform v1.5.7
- hashicorp/awscc v1.1.0
- hashicorp/aws v5.33.0

### Affected Resource(s)

* awscc provider itself

### Terraform Configuration Files

```hcl
provider "awscc" {
  assume_role = {
    role_arn = "insert-your-arn"
  }
  region = "eu-west-1"
}
```

### Panic Output

```sh
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain
│ more details.
╵
Stack trace from the terraform-provider-awscc_v1.1.0_x5 plugin:
panic: Go Duration ValueDuration Error
Duration string value is null
goroutine 54 [running]:
github.com/hashicorp/terraform-provider-awscc/internal/errs.Must[...](...)
	github.com/hashicorp/terraform-provider-awscc/internal/errs/must.go:13
github.com/hashicorp/terraform-provider-awscc/internal/errs/diag.Must[...](...)
	github.com/hashicorp/terraform-provider-awscc/internal/errs/diag/must.go:17
github.com/hashicorp/terraform-provider-awscc/internal/provider.assumeRoleData.Config({{{0x0, {0x0, 0x0}}}, {0x0, {0x0, 0x0}}, {{0x0, {0x0, 0x0}}}, {{0x0, ...}, ...}, ...})
	github.com/hashicorp/terraform-provider-awscc/internal/provider/provider.go:298 +0x63d
github.com/hashicorp/terraform-provider-awscc/internal/provider.newProviderData({0x31ad308, 0xc0040e9b00}, 0xc000490f00)
	github.com/hashicorp/terraform-provider-awscc/internal/provider/provider.go:480 +0xb38
github.com/hashicorp/terraform-provider-awscc/internal/provider.(*ccProvider).Configure(0xc0000a4058, {0x31ad308, 0xc0040e9b00}, {{0xc002c06940, 0x5}, {{{0x31b36d0, 0xc0040f3cb0}, {0x2105720, 0xc0040f3470}}, {0x31e0a88, ...}}, ...}, ...)
	github.com/hashicorp/terraform-provider-awscc/internal/provider/provider.go:373 +0x21f
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ConfigureProvider(0xc000490000, {0x31ad308, 0xc0040e9b00}, 0xc002b340a0, 0xc003253640)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_configureprovider.go:18 +0x132
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ConfigureProvider(0xc000490000, {0x31ad308?, 0xc0040e9a10?}, 0xc004988960)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_configureprovider.go:39 +0x2c5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0xc0000de0a0, {0x31ad308?, 0xc0040e91d0?}, 0xc002a7fae0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:559 +0x35a
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x221e0c0, 0xc0000de0a0}, {0x31ad308, 0xc0040e91d0}, 0xc002c30a80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:464 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00048c000, {0x31ad308, 0xc0040e9140}, {0x31de600, 0xc0001fc000}, 0xc001c58b40, 0xc0000dbad0, 0x40af130, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc00048c000, {0x31de600, 0xc0001fc000}, 0xc001c58b40)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 68
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125
Error: The terraform-provider-awscc_v1.1.0_x5 plugin crashed!
```

### Expected Behavior

Previous behaviour is maintained; no panic

### Actual Behavior

Panic

### Steps to Reproduce

terraform plan 

### Important Factoids

Previously assume-role in the awscc provider config did not require a duration, it was simply an optional value. As of 5 days ago however "Must" was added, implying that it is now required to set this or the provider will crash.

It's still listed as optional on the docs even 
```sh
Optional:

[duration](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs#duration) (String) The duration, between 15 minutes and 12 hours, of the role session. Valid time units are ns, us (or µs), ms, s, h, or m.
```

This is a breaking change, though we did jump a minor version so if that's the intention then it's fine. I'd like to suggest either
1. a default value to be used here if not given so that we do not panic -or-
2. the docs are updated to reflect that this value is now most definitely not optional

Please correct me if I'm missed something.

### References

Line:
https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/provider/provider.go#L298 

Change:
https://github.com/hashicorp/terraform-provider-awscc/commit/fcb50e610b28c07612135abca04195e4c1155c67

Docs:
https://registry.terraform.io/providers/hashicorp/awscc/latest/docs#assume-role

* #0000

**Comment by bootswithdefer** [comment] 2024-06-11 15:15
Duplicate of #1808

**Closed** 2024-06-13 17:42 UTC
Labels: bug, provider, crash
